version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_container
    restart: always
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "mssql+pyodbc://SA:Eason901215!123@192.168.83.4/Data_Base?driver=ODBC+Driver+17+for+SQL+Server"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_DRIVER: ${DB_DRIVER}
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: react_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network: {}


      
  #test:
    #build: ./test
    #container_name: test_container
    #restart: always
    #ports:
      #- "5002:5002"

