apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dividend-backend
  template:
    metadata:
      labels:
        app: dividend-backend
    spec:
      containers:
      - name: backend
        image: eason20011215/dividendtracker-backend:v1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: dividend-backend
  ports:
  - port: 80
    targetPort: 5001
  type: NodePort
