apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: dividend-frontend
spec:
  containers:
  - name: frontend
    image: eason20011215/dividendtracker-frontend:v1.4
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    #envFrom:
    #- configMapRef:
        #name: frontend-config  # Reference the ConfigMap created earlier
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: dividend-frontend
  ports:
  - port: 85
    targetPort: 3000
  type: NodePort
