create_backend_deployment:
	kubectl apply -f backend-config.yaml
	kubectl apply -f backend-secret.yaml
	kubectl apply -f backend.yml
create_frontend_deployment:
#	kubectl apply -f frontend-config.yaml
	kubectl apply -f frontend.yml
